# VEH1c: Con matrícula concreta y nombre de titular (variante de VEH01)

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX schema: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?owner ?ownerName
WHERE {
    ?vehicle edintveh:registeredOwner ?owner .
	?vehicle edintveh:licensePlateNumber "MATRICULA"^^xsd:string .
    OPTIONAL {
        ?owner schema:name | rdfs:label ?ownerName .
    }
}
