# VEH5a: Con autorización concreta (variante de VEH05)

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX zone: <https://edint.es/def/zona-regulatoria#>

SELECT ?zone
WHERE {
    <URI_DE_LA_AUTORIZACION> edintveh:authorisesInZone ?zone .
}
