
# VEH5: ¿En que zona permite operar una autorización?


PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX zone: <https://edint.es/def/zona-regulatoria#>

SELECT ?permit ?zone
WHERE {
    ?permit a edintveh:Permit ;
            edintveh:authorisesInZone ?zone .
}


# Con autorización concreta:

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX zone: <https://edint.es/def/zona-regulatoria#>

SELECT ?zone
WHERE {
    <URI_DE_LA_AUTORIZACION> edintveh:authorisesInZone ?zone .
}
