
# VEH1:  ¿Quién es el titular de un vehículo?

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX schema: <https://schema.org/>

SELECT ?vehicle ?owner
WHERE {
    ?vehicle a edintveh:Vehicle ;
             edintveh:registeredOwner ?owner .
}


# Con vehículo concreto

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>

SELECT ?owner
WHERE {
    <URI_DEL_VEHICULO> edintveh:registeredOwner ?owner .
}


# Con nombre de titular 

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX schema: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?owner ?ownerName
WHERE {
    <URI_DEL_VEHICULO> edintveh:registeredOwner ?owner .

    OPTIONAL {
        ?owner schema:name | rdfs:label ?ownerName .
    }
}


# Con matrícula concreta y nombre de titular

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>
PREFIX schema: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?owner ?ownerName
WHERE {
    ?vehicle edintveh:registeredOwner ?owner .
	?vehicle edintveh:licensePlateNumber "MATRICULA"^^xsd:string .
    OPTIONAL {
        ?owner schema:name | rdfs:label ?ownerName .
    }
}






