
# VEH11: ¿Qué vehículo es autorizado por una autorización determinada?

PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>

SELECT ?vehicle
WHERE {
    <URI_DE_LA_AUTORIZACION> edintveh:authorisesVehicle ?vehicle .
}


